### ISSUE TITLE
"Error: ENOENT: no such file or directory, open '/config/EasyESP_MQTTDisc.txt'"

### ISSUE THREAD

**Issue by blarrkan** [KnatteAnka/NodeRED_ESPEASY_AutoDiscovery#1]
I have followed your Main install guide. It seems the NodeRed flow is missing a config file. Where can that be found? I dont read anything in your guide where is should be found.

Nodered is run in a docker environment.
![image](https://user-images.githubusercontent.com/5886119/109624303-56d63600-7b3e-11eb-830b-d2bc68341414.png)

**Comment by KnatteAnka** [comment]
Press save list once ant it will be fixed will add it to the guide

**Comment by blb4github** [comment]
I'm looking into this niche project as easier alternative than configuring all manual in HA or moving all my ESPEasy nodes to ESPhome. On one way or the other the EasyESP_MQTTDisc.txt file can't be created. If tried this in NR install on raspberry pi and on NR install in a docker container on my QNAP nas, the file isn't there after pushing the save list inject.

Update: it did have to do with location of the file, I did have to change the path to fit it in the file structure.
