### ISSUE TITLE
Add units

### ISSUE THREAD

**Issue by Miau09** [KnatteAnka/NodeRED_ESPEASY_AutoDiscovery#2]
Took me some hours to figure this out (new to node-red), so I thought it might help others as well:

It was very confusing, to have the units defined inside the function-node, but the ones which are used during the execution are defined in the settings-inject-node.

Is it possible to delete the stuff in the function-node, that is defined in the settings-node?

btw, is it possible to delete node-red after everything is imported in home assistant?
or will the discovered devices be lost?

**Comment by KnatteAnka** [comment]
At Advance Settings it say that you should edit the inject node settings. but have highlighted and clarified that in the text.

**Comment by KnatteAnka** [comment]
at next version i will add comment inside function node to not edit those values but in the settings inject node

**Comment by Miau09** [comment]
I have read the advanced settings instruction, but seems like the lack of knowledge for node-red prevented me from understanding what you meant :)

anyway, working like a charm, thx.
Saved me a lot of time, and I would have definitely missed the "device" grouping if i had to create the entities myself.

**Comment by Miau09** [comment]
oh, and btw. correct unit for the pressure is "hPa", not "hPA".
Maybe you can fix this as well, influxdb "needs" the correct spelling

**Comment by KnatteAnka** [comment]
Done with release 2.2.2 :) but guess you have already done it :)
